parameters:
#    ciudad.example.class: Hechizo\CiudadBundle\Example

services:
#    ciudad.example:
#        class: %ciudad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
