pagina_ayuda:
    path: /ayuda
    defaults: { template: 'OfertaBundle:Templeate:ayuda.html.twig' }
    
pagina_privacidad:
    path: /privacidad
    defaults: { template: 'OfertaBundle:Templeate:privacidad.html.twig' }
    
pagina_condiciones:
    path: /terminos-y-condiciones
    defaults: { template: 'OfertaBundle:Templeate:condiciones.html.twig' }

pagina_contacto:
    path: /contacto
    defaults: { template: 'OfertaBundle:Templeate:contacto.html.twig' }

pagina_sobre_nosotros:
    path: /sobre-nosotros
    defaults: { template: 'OfertaBundle:Templeate:sobre-nosotros.html.twig' }