parameters:
#    tienda.example.class: Hechizo\TiendaBundle\Example

services:
#    tienda.example:
#        class: %tienda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
